[tool.ruff]
line-length = 120
target-version = "py38"


[tool.pylint.messages_control]
max-line-length = 120

[tool.pylint.pylint_opts]
disable = ["missing-class-docstring", "missing-module-docstring"]

